version: '3'

services:
  db:
    image: postgres
    restart: always
    ports:
      - "${DB_EXPOSED_PORT}:${DB_INTERNAL_PORT}"
    environment:
      - POSTGRES_USER=${DB_USER}
      - POSTGRES_PASSWORD=${DB_PASSWORD}
      - POSTGRES_DB=${DB_NAME}
    networks:
      - random_network

  pgadmin:
    image: dpage/pgadmin4
    networks:
      - random_network
    ports:
      - "${PGADMIN_EXPOSED_PORT}:80"
    environment:
      - PGADMIN_DEFAULT_EMAIL=${PGADMIN_EMAIL}
      - PGADMIN_DEFAULT_PASSWORD=${PGADMIN_PASSWORD}

  lint:
    build:
      context: .
      dockerfile: docker/test.Dockerfile
      target: lint

  e2e:
    build:
      context: .
      dockerfile: docker/test.Dockerfile
      target: e2e
    environment:
      - HOST=server
      - PORT=${SERVER_INTERNAL_PORT}
      - DATABASE_URL=postgres://${DB_USER}:${DB_PASSWORD}@${DB_HOST}:${DB_INTERNAL_PORT}/${DB_NAME}?schema=public&connect_timeout=${DB_CONNECTION_TIMEOUT}
    networks:
      - random_network

  server:
    build:
      context: .
      dockerfile: docker/server.Dockerfile
      target: run
    ports:
      - "${SERVER_EXPOSED_PORT}:${SERVER_INTERNAL_PORT}"
    environment:
      - PORT=${SERVER_INTERNAL_PORT}
      - DATABASE_URL=postgres://${DB_USER}:${DB_PASSWORD}@${DB_HOST}:${DB_INTERNAL_PORT}/${DB_NAME}?schema=public&connect_timeout=${DB_CONNECTION_TIMEOUT}
    networks:
      - random_network

networks:
  random_network:
    driver: bridge
