version: '3'

services:
  db:
    image: postgres
    restart: always
    environment:
      - POSTGRES_PASSWORD=postgres
    container_name: postgres
    volumes:
      - ./pgdata:/var/lib/postgresql/data
    ports:
      - '5400:5432'
  server-lint:
    build:
      context: .
      dockerfile: docker/server.Dockerfile
      target: lint
  server:
    build:
      context: .
      dockerfile: docker/server.Dockerfile
      target: run
    ports:
      - "${PORT}:3000"
    environment:
      - NODE_ENV=development
      - PORT=${PORT:-3000}
    networks:
      - ntwrk
  e2e:
    build:
      context: .
      dockerfile: docker/server.e2e.Dockerfile
      target: test
    depends_on:
      - server
    environment:
      - HOST=${HOST:-server}
      - PORT=${PORT:-3000}
    networks:
      - ntwrk_network

networks:
  ntwrk_network:
    driver: bridge
